company: HostLink
company_logo: api/images/logo.png
company_url: https://www.hostlink.com.hk

two_step_verification: false

biometric_authentication: false
2-step verification white list: null
footer_content:
copyright_year: 2023
copyright_url: https://www.hostlink.com.hk
copyright_name: HostLink

login_version: v1

search-form: false

domain:

smtp:
smtp-username:
smtp-password:
smtp-port:
smtp-auto-tls: true

return-path:

password-length: 6

log-save: true

auth-lockout: true

authentication_lock: true
authentication_lock_time: 180

menu_width: 280

access_token_expire: 86400

theme_customizer: true