company: HostLink
company_logo: /vx/images/logo.png
company_url: https://www.hostlink.com.hk

2-step verification: 0
2-step verification white list: null
footer_content:
copyright_year: 2021
copyright_url: https://www.hostlink.com.hk
copyright_name: HostLink

login_version: v1


search-form: false
default-skin: skin-blue

domain:

smtp:
smtp-username:
smtp-password:
smtp-port:
smtp-auto-tls: 1

return-path:

password-length: 6

log-save: true

development: true

auth-lockout: true
